name: Run tests and deploy to GCP

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push

      - name: Debug mock Secrets
        run: |
          if [ -n "${{ secrets.HOST }}" ]; then
            echo "HOST is set"
          else
            echo "HOST is not set"
          fi
          if [ -n "${{ secrets.USERNAME }}" ]; then
            echo "USERNAME is set"
          else
            echo "USERNAME is not set"
          fi
          if [ -n "${{ secrets.SSH_KEY }}" ]; then
            echo "SSH_KEY is set"
          else
            echo "SSH_KEY is not set"
          fi

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          debug: true
          script: |
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
